In [22]:
from train_and_eval import preprocess_data

ImportError: cannot import name 'load_ff6' from 'data' (c:\Users\firdavs\Documents\BEM-114\final_project\data.py)

In [21]:
ff6

          date  Mkt-RF   SMB   HML   RMW   CMA     RF   Mom
8940  19990104   -0.19  0.13  0.41 -0.18 -0.44  0.019 -1.49
8941  19990105    1.10 -0.85 -0.09 -0.27 -0.33  0.019 -0.97
8942  19990106    2.10 -0.73 -0.60 -0.50 -1.09  0.019 -1.17
8943  19990107   -0.07  0.37 -0.29 -0.67 -0.85  0.019 -0.72
8944  19990108    0.45  0.19  0.28 -0.70 -0.42  0.019 -0.16
...        ...     ...   ...   ...   ...   ...    ...   ...
9187  19991227   -0.21  0.63 -0.66  0.26 -0.02  0.020  0.78
9188  19991228    0.21  0.47 -0.07 -0.25  0.47  0.020  0.28
9189  19991229    0.64  1.00  0.02 -0.83 -0.65  0.020 -0.19
9190  19991230    0.08  0.13 -0.04  0.38 -0.21  0.020 -0.75
9191  19991231    0.52  1.40  0.48 -0.53  0.12  0.020  0.36

[252 rows x 8 columns]

In [ ]:
import matplotlib.pyplot as plt

# Simple plot

plt.plot([1, 2, 3, 4], [1, 4, 9, 16])
# plt.show()

# Save plot to file
plt.savefig('plot.png')
plt.show()

In [ ]:
data = get_data()

NameError: name 'get_data' is not defined